[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "stable"                                                   # try with stable
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
